// Generated by CoffeeScript 2.7.0
  //###########################################################
  //region imports
import {
  RPCPostClient
} from "thingy-post-rpc-client";

//endregion

  //###########################################################
export var RPCAuthMasterClient = class RPCAuthMasterClient extends RPCPostClient {
  constructor(o) {
    super(o);
  }

  //#######################################################
  addClient(clientPublicKey) {
    var args, authType, func;
    authType = "masterSignature";
    args = {clientPublicKey};
    func = "addClientToServe";
    return this.doRPC(func, args, authType);
  }

  removeClient(clientPublicKey) {
    var args, authType, func;
    authType = "masterSignature";
    args = {clientPublicKey};
    func = "removeClientToServe";
    return this.doRPC(func, args, authType);
  }

  getClients() {
    var args, authType, func;
    authType = "masterSignature";
    args = {};
    func = "getClientsToServe";
    return this.doRPC(func, args, authType);
  }

};
